version: "3"

services:
  # Database
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vulcnn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis for task queue
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  # Main API Service
  api:
    build: ./backend/api
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@postgres:5432/vulcnn
      - JWT_SECRET_KEY=your-secret-key
      - UPLOAD_FOLDER=/app/data/uploads
    volumes:
      - ./data:/app/data

  # Normalization Service
  normalization:
    build: ./backend/normalization_service
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data

  # PDG Generator Service
  pdg-generator:
    build: ./backend/pdg_generator_service
    ports:
      - "5002:5002"
    volumes:
      - ./data:/app/data

  # Image Generator Service
  image-generator:
    build: ./backend/image_generator_service
    ports:
      - "5003:5003"
    volumes:
      - ./data:/app/data
      - ./models:/app/models

  # Prediction Service
  prediction:
    build: ./backend/prediction_service
    ports:
      - "5004:5004"
    volumes:
      - ./data:/app/data
      - ./models:/app/models

  # Results Service
  results:
    build: ./backend/results_service
    ports:
      - "5005:5005"
    volumes:
      - ./data:/app/data

  # Celery Worker
  worker:
    build: ./backend/api
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
      - api
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@postgres:5432/vulcnn
    volumes:
      - ./data:/app/data

volumes:
  postgres_data:
