import os
import shutil

def generate_pdg_from_file(pdg_file_path, output_path):
    """
    Process the PDG file generated by Joern and save it to the output path
    
    Args:
        pdg_file_path (str): Path to the PDG file generated by Joern
        output_path (str): Where to save the PDG
        
    Returns:
        bool: True if successful, False otherwise
    """
    try:
        if not pdg_file_path or not os.path.exists(pdg_file_path):
            print(f"PDG file not found: {pdg_file_path}")
            return False
        # Create output directory if it doesn't exist
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        # Simply copy the PDG file to the output path
        shutil.copy2(pdg_file_path, output_path)
        
        print(f"PDG file copied from {pdg_file_path} to {output_path}")

        return True
    
    except Exception as e:
        print(f"Error generating PDG: {str(e)}")
        return False